export { default as Navbar} from './Navbar'
export { default as Home} from './home/Home'
export { default as Exchange} from './Exchange'
export { default as Cryptocurrencies} from './cryptoCurrency/Cryptocurrencies'
export { default as CryptoDetails} from './cryptoDetails/CryptoDetails'
export { default as News} from './news/News'
