export { default as Navbar} from './navbar/Navbar'
export { default as Home} from './home/Home'
export { default as Exchange} from './exchange/Exchange'
export { default as Cryptocurrencies} from './cryptoCurrency/Cryptocurrencies'
export { default as CryptoDetails} from './cryptoDetails/CryptoDetails'
export { default as News} from './news/News'
